No series card

diff --git a/azure-pipelines.yml b/azure-pipelines.yml
--- a/azure-pipelines.yml
+++ b/azure-pipelines.yml
@@ -40,25 +40,25 @@ steps:
         # Tag the Docker image for Docker Hub
         sudo docker tag pmis agilesam/pmis:latest
 
-        # # Log in to Docker Hub
-        # echo "$DOCKER_HUB_PASSWORD" | sudo docker login -u "$DOCKER_HUB_USERNAME" --password-stdin
+        # Log in to Docker Hub
+        echo "$DOCKER_HUB_PASSWORD" | sudo docker login -u "$DOCKER_HUB_USERNAME" --password-stdin
 
-        # # Push the Docker image to Docker Hub
-        # sudo docker push agilesam/pmis:latest
+        # Push the Docker image to Docker Hub
+        sudo docker push agilesam/pmis:latest
 
-        # # Stop and remove the existing container if it exists
-        # sudo docker stop pmis-core || true
-        # sudo docker rm pmis-core || true
+        # Stop and remove the existing container if it exists
+        sudo docker stop pmis-core || true
+        sudo docker rm pmis-core || true
 
-        # # Run the new Docker container
-        # sudo docker run --name pmis-core -p 4000:3000 -d agilesam/pmis:latest
+        # Run the new Docker container
+        sudo docker run --name pmis-core -p 4000:3000 -d agilesam/pmis:latest
 
-        # # Clean up Docker images and builder
-        # sudo docker image prune -af
-        # sudo docker builder prune -f
+        # Clean up Docker images and builder
+        sudo docker image prune -af
+        sudo docker builder prune -f
 
-        # # Restart Nginx to apply any changes
-        # sudo systemctl restart nginx
+        # Restart Nginx to apply any changes
+        sudo systemctl restart nginx
 
         echo "Deployment completed successfully"
       EOF
