Push to server 2

diff --git a/pipeline test.yml b/pipeline test.yml
--- a/pipeline test.yml
+++ b/pipeline test.yml
@@ -35,10 +35,10 @@ steps:
         git pull
 
         # Build the Docker image with no cache
-        sudo docker build --no-cache -t pmis .
+        sudo docker build --no-cache --build-arg NEXT_PUBLIC_API_BASE_URL=https://pmistest-api.treasury.go.ke/ -t agilesam/pmis:latest .
 
-        # Tag the Docker image for Docker Hub
-        sudo docker tag pmis agilesam/pmis:latest
+
+        sudo docker build --no-cache --build-arg NEXT_PUBLIC_API_BASE_URL=https://tntapi.agilebiz.co.ke/ -t pmis .
 
         # Log in to Docker Hub
         echo "$DOCKER_HUB_PASSWORD" | sudo docker login -u "$DOCKER_HUB_USERNAME" --password-stdin
@@ -46,19 +46,19 @@ steps:
         # Push the Docker image to Docker Hub
         sudo docker push agilesam/pmis:latest
 
-        # # Stop and remove the existing container if it exists
-        # sudo docker stop pmis-core || true
-        # sudo docker rm pmis-core || true
+        # Stop and remove the existing container if it exists
+        sudo docker stop pmis-core || true
+        sudo docker rm pmis-core || true
 
-        # # Run the new Docker container
-        # sudo docker run --name pmis-core -p 4000:3000 -d agilesam/pmis:latest
+        # Run the new Docker container
+        sudo docker run --name pmis-core -p 4000:3000 -d pmis
 
-        # # Clean up Docker images and builder
-        # sudo docker image prune -af
-        # sudo docker builder prune -f
+        # Clean up Docker images and builder
+        sudo docker image prune -af
+        sudo docker builder prune -f
 
-        # # Restart Nginx to apply any changes
-        # sudo systemctl restart nginx
+        # Restart Nginx to apply any changes
+        sudo systemctl restart nginx
 
         echo "Deployment completed successfully"
       EOF
